* Results for 1: 652,094,1-6,521,124 (+)

** *miRBase name:* [[http://mirbase.org/cgi-bin/mirna_entry.pl?acc=MI0005393][ath-MIR837]]
** *Chromosome:* 1
** *Position:* 652,094,1-6,521,124 (184 nt)
** *Strand:* +
** *G+C:* 22.83 %
** *miRNA sequence:* AUCAGUUUCUUGUUCGUUUCA
** *miRNA precursor:*
=
UUUUUGAUAAAUACUUUUGUUUGCUUACAAGUAUAAAGUCAUCAUGUUUUUUUCAUCAGU
(((((((((((((.(((((((((.((((((((((((((((.(((((((((((.(((((((

UUCUUGUUCGUUUCAAAAUUAUGAUUUUUGUUUACUUACACUCAUAAUCUUGAAACGAAC
((.(((((((((((((.(((((((....(((......))).))))))).)))))))))))

AAAAAACUGAUGGAAAAACAUGAGGACUUUAUACUUGUAAAUAAAUAAAAAUAUUUAUUA
)).)))))))))))))))))))).)))))))))))))))).))))))))).)))))))))

GAAA
))))
=
This stem-loop structure is the MFE structure.
** *Stability of the secondary structure of the precursor:* /MFE/ -85.20 kcal/mol | /AMFE/ -46.30 | /MFEI/ -2.03
** *Total number of reads mapped to the precursor:* 108

* Results for 1: 669,542,0-6,695,609 (-)

** *miRBase name:* [[http://mirbase.org/cgi-bin/mirna_entry.pl?acc=MI0000982][ath-MIR169h]]
** *Chromosome:* 1
** *Position:* 669,542,0-6,695,609 (190 nt)
** *Strand:* -
** *G+C:* 39.47 %
** *miRNA sequence:* UAGCCAAGGAUGACUUGCCUG
** *miRNA precursor:*
=
UCAUAUAAGAGAAAAUGGUGACAUGAAGAAUGAGAACUUGUGUGGUAGCCAAGGAUGACU
.((...((((((((...((((.((((((((((((((.((((.(((((((((((((.((((

UGCCUGCGUUUUAGACCAUAUAUAUCAAAGACUCACUCGAUCGAUAGUCUUAGAGUUGGU
.(((((.......(((((..((..((.((((((...((....)).)))))).))..))..

UGGUCGUCAGGCAGUCUCCUUGGCUAUUCAAACAAUUCUCAUUCUCUUCAUUCACAUUUC
)))))..))))))))))))))))))).))).)))))))))))..))))))))))).))))

UCUUUUUUGG
))))...)).
=
This stem-loop structure is the MFE structure.
** *Stability of the secondary structure of the precursor:* /MFE/ -79.00 kcal/mol | /AMFE/ -41.58 | /MFEI/ -1.05
** *Total number of reads mapped to the precursor:* 389

* Results for 4: 3,698,31-,370,012 (-)

** *miRBase name:* [[http://mirbase.org/cgi-bin/mirna_entry.pl?acc=MI0000200][ath-MIR165b]]
** *Chromosome:* 4
** *Position:* 3,698,31-,370,012 (182 nt)
** *Strand:* -
** *G+C:* 37.91 %
** *miRNA sequence:* UCGGACCAGGCUUCAUCCCCC
** *miRNA precursor:*
=
UGAAGAGGCUAUUUCUGUUGUGGGGAAUGUUGUUUGGAUCGAGGAUAUCAUAAACGCAUA
....(((((.(((.((((((.((((.(((..((((((.((((.((((((((....((((.

CACAUGUUUAUAUGUUAUGAUGCAUUAUAUGACUGAUGUAAUGUACAUAUAUAUACAUAC
...((((..((((((.(((.((((((((((.....)))))))))))))))))))))))..

AUGCCACAUGGUAUCGUCGGACCAGGCUUCAUCCCCCUCAACAUGUUAAUUGCCUUCAAU
))))...)))))))).)))).))))))..))).)))).))))).)..))).)))))....

CA
..
=
This stem-loop structure is the MFE structure.
** *Stability of the secondary structure of the precursor:* /MFE/ -66.50 kcal/mol | /AMFE/ -36.54 | /MFEI/ -0.96
** *Total number of reads mapped to the precursor:* 223338

* Results for 4: 102,391,2-1,024,149 (+)

** *miRBase name:* [[http://mirbase.org/cgi-bin/mirna_entry.pl?acc=MI0019217][ath-MIR5635d]]
** *Chromosome:* 4
** *Position:* 102,391,2-1,024,149 (238 nt)
** *Strand:* +
** *G+C:* 39.08 %
** *miRNA sequence:* UGUUAAGGAGUGUUAACGGUG
** *miRNA precursor:*
=
AGUUGACUUCUAAUUUAACCUAUAAGUUAUCGUUGACACGGCCAAAUCGACUCACCAUUA
.((((((((((((((((((.(((((.(((((((((((.(((((((((.((((((((.(((

ACACUUCUUAACAGCUCUCCUAACAGCGUAACUAACAACUGUUUUUGUCCUUAAACCAAC
(((((((((((((((.(((((((((((.................................

GAUAACGGCUGUUAGGCCAUGUUUUGUAACGGCUGUUAGGAGCGCUGUUAAGGAGUGUUA
...............................))))))))))).)))))))))))))))))

ACGGUGAGUCUAUUUGGCUGGGUCAACGAUAAAUUAUAUGUUAAAUUAGAAGUCAACA
).)))))))).))))))))).))))))))))).))))).)))))))))))))))))).
=
** *Stability of the secondary structure of the precursor:* /MFE/ -135.40 kcal/mol | /AMFE/ -56.89 | /MFEI/ -1.46
** *Total number of reads mapped to the precursor:* 294

* Results for 4: 104,680,4-1,046,983 (-)

** *miRBase name:* [[http://mirbase.org/cgi-bin/mirna_entry.pl?acc=MI0013366][ath-MIR2936]]
** *Chromosome:* 4
** *Position:* 104,680,4-1,046,983 (180 nt)
** *Strand:* -
** *G+C:* 41.11 %
** *miRNA sequence:* CUUGAGAGAGAGAACACAGACG
** *miRNA precursor:*
=
CCAUUUUCGAAAGCCUUGAGAGAGAGAACACAGACGAUACCAACUUUCUUCAAUCUCGUU
(((((((((((...((((((((((((((.((((((........(((.((((....(((((

GCCGCAGUAUAAUUAUCUCAUUCCUCGGAUAUAUCUCUCCUUCUGCGGCGGCGACAAGAA
(((((((..............((....)).............))))))))))))...)))

GCUACAAGAAUAAAAAGUCUGUUUUCUCUCUUUUCAAGAAACCACUUACUUCGAAAAUGG
)....)))........)))))).))))))).)))))))...........)))))))))))

=
This stem-loop structure is the MFE structure.
** *Stability of the secondary structure of the precursor:* /MFE/ -60.40 kcal/mol | /AMFE/ -33.56 | /MFEI/ -0.82
** *Total number of reads mapped to the precursor:* 5

