* Results for 1: 652,094,1-6,521,124 (+)

*miRBase name:* [[http://mirbase.org/cgi-bin/mirna_entry.pl?acc=MI0005393][ath-MIR837]]
*Chromosome:* 1
*Position:* 652,094,1-6,521,124 (184 nt)
*Strand:* +
*G+C content:* 22.83 %
*miRNA sequence:* AUCAGUUUCUUGUUCGUUUCA
*miRNA precursor:*
=
UUUUUGAUAAAUACUUUUGUUUGCUUACAAGUAUAAAGUCAUCAUGUUUUUUUCAUCAGU
(((((((((((((.(((((((((.((((((((((((((((.(((((((((((.(((((((

UUCUUGUUCGUUUCAAAAUUAUGAUUUUUGUUUACUUACACUCAUAAUCUUGAAACGAAC
((.(((((((((((((.(((((((....(((......))).))))))).)))))))))))

AAAAAACUGAUGGAAAAACAUGAGGACUUUAUACUUGUAAAUAAAUAAAAAUAUUUAUUA
)).)))))))))))))))))))).)))))))))))))))).))))))))).)))))))))

GAAA
))))
=
This stem-loop structure is the MFE structure.
*Stability of the secondary structure of the precursor:* /MFE/ -85.20 kcal/mol | /AMFE/ -46.30 | /MFEI/ -2.03
*Total number of reads mapped to the precursor:* 108
=
UUUUUGAUAAAUACUUUUGUUUGCUUACAAGUAUAAAGUCAUCAUGUUUUUUUCAUCAGUUUCUUGUUCGUUUCAAAAUUAUGAUUUUUGUUUACUUACACUCAUAAUCUUGAAACGAACAAAAAACUGAUGGAAAAACAUGAGGACUUUAUACUUGUAAAUAAAUAAAAAUAUUUAUUAGAAA
(((((((((((((.(((((((((.((((((((((((((((.(((((((((((.(((((((((.(((((((((((((.(((((((....(((......))).))))))).))))))))))))).)))))))))))))))))))).)))))))))))))))).))))))))).)))))))))))))
                                                      <------miRBase------>                                     <------miRBase------>                                                   
...................................................*********************................................................................................................................ length=21 depth=2
....................................................*********************............................................................................................................... length=21 depth=8
......................................................AUCAGUUUCUUGUUCGUUUCA............................................................................................................. length=21 depth=18
...........................................................................................................*********************........................................................ length=21 depth=3
................................................................................................................*********************................................................... length=21 depth=2
.....................................................................................................................................*********************.............................. length=21 depth=3
.....................................................................................................................................************************........................... length=24 depth=37
........................................................................................................................................*********************........................... length=21 depth=21
............................................................................................................................................*********************....................... length=21 depth=3
=

* Results for 1: 669,542,0-6,695,609 (-)

*miRBase name:* [[http://mirbase.org/cgi-bin/mirna_entry.pl?acc=MI0000982][ath-MIR169h]]
*Chromosome:* 1
*Position:* 669,542,0-6,695,609 (190 nt)
*Strand:* -
*G+C content:* 39.47 %
*miRNA sequence:* UAGCCAAGGAUGACUUGCCUG
*miRNA precursor:*
=
UCAUAUAAGAGAAAAUGGUGACAUGAAGAAUGAGAACUUGUGUGGUAGCCAAGGAUGACU
.((...((((((((...((((.((((((((((((((.((((.(((((((((((((.((((

UGCCUGCGUUUUAGACCAUAUAUAUCAAAGACUCACUCGAUCGAUAGUCUUAGAGUUGGU
.(((((.......(((((..((..((.((((((...((....)).)))))).))..))..

UGGUCGUCAGGCAGUCUCCUUGGCUAUUCAAACAAUUCUCAUUCUCUUCAUUCACAUUUC
)))))..))))))))))))))))))).))).)))))))))))..))))))))))).))))

UCUUUUUUGG
))))...)).
=
This stem-loop structure is the MFE structure.
*Stability of the secondary structure of the precursor:* /MFE/ -79.00 kcal/mol | /AMFE/ -41.58 | /MFEI/ -1.05
*Total number of reads mapped to the precursor:* 389
=
UCAUAUAAGAGAAAAUGGUGACAUGAAGAAUGAGAACUUGUGUGGUAGCCAAGGAUGACUUGCCUGCGUUUUAGACCAUAUAUAUCAAAGACUCACUCGAUCGAUAGUCUUAGAGUUGGUUGGUCGUCAGGCAGUCUCCUUGGCUAUUCAAACAAUUCUCAUUCUCUUCAUUCACAUUUCUCUUUUUUGG
.((...((((((((...((((.((((((((((((((.((((.(((((((((((((.((((.(((((.......(((((..((..((.((((((...((....)).)))))).))..))..)))))..))))))))))))))))))).))).)))))))))))..))))))))))).))))))))...)).
                                             <------miRBase------>                                                                                                                            
..........................*******************................................................................................................................................................. length=19 depth=17
...........................................*********************.............................................................................................................................. length=21 depth=7
...........................................**********************............................................................................................................................. length=22 depth=8
...........................................***********************............................................................................................................................ length=23 depth=7
.............................................*******************.............................................................................................................................. length=19 depth=4
.............................................********************............................................................................................................................. length=20 depth=44
.............................................UAGCCAAGGAUGACUUGCCUG............................................................................................................................ length=21 depth=245
.................................................................................................................................******************........................................... length=18 depth=8
.................................................................................................................................*******************.......................................... length=19 depth=26
.................................................................................................................................********************......................................... length=20 depth=9
=

* Results for 4: 3,698,31-,370,012 (-)

*miRBase name:* [[http://mirbase.org/cgi-bin/mirna_entry.pl?acc=MI0000200][ath-MIR165b]]
*Chromosome:* 4
*Position:* 3,698,31-,370,012 (182 nt)
*Strand:* -
*G+C content:* 37.91 %
*miRNA sequence:* UCGGACCAGGCUUCAUCCCCC
*miRNA precursor:*
=
UGAAGAGGCUAUUUCUGUUGUGGGGAAUGUUGUUUGGAUCGAGGAUAUCAUAAACGCAUA
....(((((.(((.((((((.((((.(((..((((((.((((.((((((((....((((.

CACAUGUUUAUAUGUUAUGAUGCAUUAUAUGACUGAUGUAAUGUACAUAUAUAUACAUAC
...((((..((((((.(((.((((((((((.....)))))))))))))))))))))))..

AUGCCACAUGGUAUCGUCGGACCAGGCUUCAUCCCCCUCAACAUGUUAAUUGCCUUCAAU
))))...)))))))).)))).))))))..))).)))).))))).)..))).)))))....

CA
..
=
This stem-loop structure is the MFE structure.
*Stability of the secondary structure of the precursor:* /MFE/ -66.50 kcal/mol | /AMFE/ -36.54 | /MFEI/ -0.96
*Total number of reads mapped to the precursor:* 223338
=
UGAAGAGGCUAUUUCUGUUGUGGGGAAUGUUGUUUGGAUCGAGGAUAUCAUAAACGCAUACACAUGUUUAUAUGUUAUGAUGCAUUAUAUGACUGAUGUAAUGUACAUAUAUAUACAUACAUGCCACAUGGUAUCGUCGGACCAGGCUUCAUCCCCCUCAACAUGUUAAUUGCCUUCAAUCA
....(((((.(((.((((((.((((.(((..((((((.((((.((((((((....((((....((((..((((((.(((.((((((((((.....)))))))))))))))))))))))..))))...)))))))).)))).))))))..))).)))).))))).)..))).)))))......
                                                                                                                                        <------miRBase------>                         
........................................................................................................................................********************.......................... length=20 depth=1251
........................................................................................................................................UCGGACCAGGCUUCAUCCCCC......................... length=21 depth=221300
=

* Results for 4: 102,391,2-1,024,149 (+)

*miRBase name:* [[http://mirbase.org/cgi-bin/mirna_entry.pl?acc=MI0019217][ath-MIR5635d]]
*Chromosome:* 4
*Position:* 102,391,2-1,024,149 (238 nt)
*Strand:* +
*G+C content:* 39.08 %
*miRNA sequence:* UGUUAAGGAGUGUUAACGGUG
*miRNA precursor:*
=
AGUUGACUUCUAAUUUAACCUAUAAGUUAUCGUUGACACGGCCAAAUCGACUCACCAUUA
.((((((((((((((((((.(((((.(((((((((((.(((((((((.((((((((.(((

ACACUUCUUAACAGCUCUCCUAACAGCGUAACUAACAACUGUUUUUGUCCUUAAACCAAC
(((((((((((((((.(((((((((((.................................

GAUAACGGCUGUUAGGCCAUGUUUUGUAACGGCUGUUAGGAGCGCUGUUAAGGAGUGUUA
...............................))))))))))).)))))))))))))))))

ACGGUGAGUCUAUUUGGCUGGGUCAACGAUAAAUUAUAUGUUAAAUUAGAAGUCAACA
).)))))))).))))))))).))))))))))).))))).)))))))))))))))))).
=
*Stability of the secondary structure of the precursor:* /MFE/ -135.40 kcal/mol | /AMFE/ -56.89 | /MFEI/ -1.46
*Total number of reads mapped to the precursor:* 294
=
.((((((((((((((((((.(((((.(((((((((((.(((((((((.((((((((.((((((((((((((((((.(((((((((((....((((((.(((((.((((..........)))).))))).))))))....((((....))))))))))))))).)))))))))))))))))).)))))))).))))))))).))))))))))).))))).)))))))))))))))))).
AGUUGACUUCUAAUUUAACCUAUAAGUUAUCGUUGACACGGCCAAAUCGACUCACCAUUAACACUUCUUAACAGCUCUCCUAACAGCGUAACUAACAACUGUUUUUGUCCUUAAACCAACGAUAACGGCUGUUAGGCCAUGUUUUGUAACGGCUGUUAGGAGCGCUGUUAAGGAGUGUUAACGGUGAGUCUAUUUGGCUGGGUCAACGAUAAAUUAUAUGUUAAAUUAGAAGUCAACA
.((((((((((((((((((.(((((.(((((((((((.(((((((((.((((((((.((((((((((((((((((.(((((((((((................................................................))))))))))).)))))))))))))))))).)))))))).))))))))).))))))))))).))))).)))))))))))))))))).
                                                                                                                                                                     <------miRBase------>                                                    
............................************************.......................................................................................................................................................................................... length=24 depth=8
........................................................************************.............................................................................................................................................................. length=24 depth=3
............................................................************************.......................................................................................................................................................... length=24 depth=3
...............................................................************************....................................................................................................................................................... length=24 depth=5
.....................................................................************************................................................................................................................................................. length=24 depth=32
..............................................................................************************........................................................................................................................................ length=24 depth=6
............................................................................................................************************.......................................................................................................... length=24 depth=10
.................................................................................................................***********************...................................................................................................... length=23 depth=5
.................................................................................................................************************..................................................................................................... length=24 depth=35
..................................................................................................................************************.................................................................................................... length=24 depth=19
.....................................................................................................................********************..................................................................................................... length=20 depth=3
..........................................................................................................................................*************************........................................................................... length=25 depth=3
............................................................................................................................................***********************........................................................................... length=23 depth=5
.............................................................................................................................................**********************........................................................................... length=22 depth=8
..............................................................................................................................................*********************........................................................................... length=21 depth=3
..............................................................................................................................................************************........................................................................ length=24 depth=7
.................................................................................................................................................******************........................................................................... length=18 depth=17
............................................................................................................................................................***********************........................................................... length=23 depth=15
.....................................................................................................................................................................************************................................................. length=24 depth=3
......................................................................................................................................................................************************................................................ length=24 depth=6
=

* Results for 4: 104,680,4-1,046,983 (-)

*miRBase name:* [[http://mirbase.org/cgi-bin/mirna_entry.pl?acc=MI0013366][ath-MIR2936]]
*Chromosome:* 4
*Position:* 104,680,4-1,046,983 (180 nt)
*Strand:* -
*G+C content:* 41.11 %
*miRNA sequence:* CUUGAGAGAGAGAACACAGACG
*miRNA precursor:*
=
CCAUUUUCGAAAGCCUUGAGAGAGAGAACACAGACGAUACCAACUUUCUUCAAUCUCGUU
(((((((((((...((((((((((((((.((((((........(((.((((....(((((

GCCGCAGUAUAAUUAUCUCAUUCCUCGGAUAUAUCUCUCCUUCUGCGGCGGCGACAAGAA
(((((((..............((....)).............))))))))))))...)))

GCUACAAGAAUAAAAAGUCUGUUUUCUCUCUUUUCAAGAAACCACUUACUUCGAAAAUGG
)....)))........)))))).))))))).)))))))...........)))))))))))

=
This stem-loop structure is the MFE structure.
*Stability of the secondary structure of the precursor:* /MFE/ -60.40 kcal/mol | /AMFE/ -33.56 | /MFEI/ -0.82
*Total number of reads mapped to the precursor:* 5
=
CCAUUUUCGAAAGCCUUGAGAGAGAGAACACAGACGAUACCAACUUUCUUCAAUCUCGUUGCCGCAGUAUAAUUAUCUCAUUCCUCGGAUAUAUCUCUCCUUCUGCGGCGGCGACAAGAAGCUACAAGAAUAAAAAGUCUGUUUUCUCUCUUUUCAAGAAACCACUUACUUCGAAAAUGG
(((((((((((...((((((((((((((.((((((........(((.((((....((((((((((((..............((....)).............))))))))))))...))))....)))........)))))).))))))).)))))))...........)))))))))))
              <------miRBase------->                                                                                                                                                
=

